language: python
python: 2.7.13
sudo: false
cache:
  directories:
    - $HOME/buildout-cache
env:
  - PLONE_VERSION=5.1.x
  - PLONE_VERSION=4.3.x
before_install:
  - mkdir -p $HOME/buildout-cache/{eggs,downloads}
  - bin/pip install -r https://raw.githubusercontent.com/plone/buildout.coredev/5.1/requirements.txt
install:
  - sed -ie "s#plone-x.x.x.cfg#plone-$PLONE_VERSION.cfg#" travis.cfg
  - bin/buildout -N -t 3 -c travis.cfg
script:
  - bin/test
